# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac85b2ddc8334a29292e8614b493f6bbf126d4b3914b84fe54fb3967b81730d023e251c25425e163bf8ba828566454597a7f248bd6610ab7af423e45b527a66

test:
  secret_key_base: 4818efdcdb54472b87d31604f0be9818c21dc129ec4df8a3fe148415d7302d5a5835b2f13e1328bf473fe6f80a76d2fdbe7894514a5fbf1db726b50b78fa91ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
